apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: manifest-tool-image-
spec:
  entrypoint: manifest-tool-image
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: manifest-tool-image
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
    steps:
    - - name: mirror-image
        templateRef:
          name: flavor-image-mirror-template
          template: "{{inputs.parameters.git_ref_type}}"
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-manifest-tool.git
          - name: git_version
            value: "{{inputs.parameters.git_version}}"
          - name: repo_name
            value: quay.io/bradfordwagner/manifest-tool
          - name: upstream_repo
            value: "{{ item.repo }}"
          - name: upstream_tag
            value: "{{ item.tag }}"
          - name: upstream_repo_name_override
            value: "{{ item.name_override }}"
        withItems:
        - { repo: 'mplatform/manifest-tool', tag: 'v1.0.3', name_override: manifest_tool }

